// Replace these with your details to enable contact actions.
const CONTACT_EMAIL = 'rtharanitharan20012@gmail.com';
const LINKEDIN_URL = 'https://www.linkedin.com/in/tharanitharan-r-01862126a/';
const episodes = [
{label:'EPISODE 01 · THE BEGINNING',title:'Who Is Tharanitharan?',text:'I am Tharanitharan, a people-focused HR professional who enjoys solving problems, supporting teams, and creating a better employee experience. I believe great workplaces are built through both empathy and thoughtful processes.'},
{label:'EPISODE 02 · THE JOURNEY',title:'From Classroom to Career',text:'My journey began with a BBA, where I secured first rank, followed by an MBA in HR & Marketing at AIMS IBS. A talent acquisition internship at GI Group and experience at RCCO Tax Needs helped me turn classroom learning into practical HR work.'},
{label:'EPISODE 03 · CURRENTLY PLAYING',title:'Life at OptInn',text:'As an HR Executive at OptInn Solutions, I coordinate recruitment and interviews, manage onboarding and BGV follow-ups, support timesheets and billing, handle vendors and travel arrangements, and contribute to employee engagement initiatives.'},
{label:'EPISODE 04 · THE TOOLKIT',title:'Skills & Superpowers',text:'My toolkit includes HR operations, candidate screening, stakeholder coordination, employee engagement, documentation, timesheet management, vendor management, and tools such as Keka, Excel, Naukri, LinkedIn, Teams, and Google Forms.'},
{label:'EPISODE 05 · THE HIGHLIGHTS',title:'Milestones',text:'Highlights of my journey include securing first rank in BBA, completing an MBA focused on HR and Marketing, and earning second runner-up at an IDEA BOX event. Each milestone inspires me to keep learning and improving.'},
{label:'EPISODE 06 · BEYOND THE DESK',title:'More Than a Job Title',text:'Outside routine HR work, I enjoy creative communication, sports and team activities, designing employee experiences, and exploring new ways to make work more engaging. The next chapter is always in progress.'}
];
const intro=document.getElementById('intro');document.getElementById('skipIntro').onclick=()=>intro.classList.add('dismiss');setTimeout(()=>intro.classList.add('dismiss'),3100);
const modal=document.getElementById('episodeModal');let previousFocus=null;document.querySelectorAll('[data-episode]').forEach(btn=>btn.addEventListener('click',()=>{previousFocus=btn;const ep=episodes[Number(btn.dataset.episode)];document.getElementById('modalLabel').textContent=ep.label;document.getElementById('modalTitle').textContent=ep.title;document.getElementById('modalText').textContent=ep.text;modal.hidden=false;document.body.style.overflow='hidden';document.getElementById('closeModal').focus()}));function closeModal(){modal.hidden=true;document.body.style.overflow='';previousFocus?.focus()}document.getElementById('closeModal').onclick=closeModal;document.querySelector('[data-close]').onclick=closeModal;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});document.getElementById('modalLink').onclick=closeModal;
document.getElementById('menu').onclick=()=>document.querySelector('.nav nav').classList.toggle('open');document.querySelectorAll('.nav nav a').forEach(a=>a.onclick=()=>document.querySelector('.nav nav').classList.remove('open'));document.getElementById('year').textContent=new Date().getFullYear();
